server:
  port: 7910
spring:
  application:
    name: auth-server
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write-dates-as-timestamps: false

logging:
  level:
    org.springframework.security: trace
eureka:
  client:
    enabled: false
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
